### PR TITLE
Feedback hw01

### PR DESCRIPTION
**Pull request by bwiernik**
Great work! See my comments in the changed files by searching for `<!--`. It looks like you inadvertently deleted the contents of README.md at some point.

### CODE REVIEW

**Comment by bwiernik** [comment]
@tylerallan Hey Tyler, after you've read my comments, please merge this. If you need a hand with the conflict resolution, let me know.

**Comment by tylerallan** [comment]
I think I do need your help with the conflict resolution. I feel like this is what led to my readme getting deleted last time.

**Comment by bwiernik** [comment]
I can't help show you how to resolve a conflict if you delete the branch first 😓

**Comment by tylerallan** [comment]
This is why I can't be trusted on github. I just press buttons and delete everything

**Comment by bwiernik** [comment]
The beauty of git is that it's usally easy to recover from.

**Comment by tylerallan** [comment]
That's true! Very nice to have a backup plan

**Pull request closed without merging**
